[settings]
class = "Names"
doc_group = "001-Route"
doc_descr = "an association between a human-readable name and an address"
doc_route = "400-names"
attributes = ""
produced_by = "names"
store_type = "singleton"
disable_go = false

[[facets]]
name = "All"
store = "Names"
actions = ["autoname", "create", "export", "update"]
mapKey = "item.Address.Hex()"

[[facets]]
name = "Custom"
store = "Names"
actions = ["autoname", "create", "delete", "export", "pin", "publish", "remove", "undelete", "update"]
mapKey = "item.Address.Hex()"

[[facets]]
name = "Prefund"
store = "Names"
actions = ["create", "export", "update"]
attributes = "dividerBefore"
mapKey = "item.Address.Hex()"

[[facets]]
name = "Regular"
store = "Names"
actions = ["autoname", "create", "export", "update"]
mapKey = "item.Address.Hex()"

[[facets]]
name = "Baddress"
store = "Names"
actions = ["create", "export"]
mapKey = "item.Address.Hex()"
