[settings]
class = "Open Approvals"
doc_group = "01-Accounts"
doc_descr = "an ERC-20 token approval granting spending permission from owner to spender"
doc_route = "122-openapprovals"
attributes = ""
produced_by = "tokens"
disable_go = true
