[settings]
class = "Statements"
contained_by = ""
doc_group = "04-Admin"
doc_descr = "A reconciliation statement"
doc_route = "118-statement"
attributes = ""
produced_by = "exports"
disable_go = true
