// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['exports']['ExportsCollection']['AccumulateItem'](arg1, arg2);
}

export function Crud(arg1, arg2, arg3) {
  return window['go']['exports']['ExportsCollection']['Crud'](arg1, arg2, arg3);
}

export function ExportData(arg1) {
  return window['go']['exports']['ExportsCollection']['ExportData'](arg1);
}

export function FetchByFacet(arg1) {
  return window['go']['exports']['ExportsCollection']['FetchByFacet'](arg1);
}

export function GetBuckets(arg1) {
  return window['go']['exports']['ExportsCollection']['GetBuckets'](arg1);
}

export function GetConfig() {
  return window['go']['exports']['ExportsCollection']['GetConfig']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['exports']['ExportsCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSummary() {
  return window['go']['exports']['ExportsCollection']['GetSummary']();
}

export function NeedsUpdate(arg1) {
  return window['go']['exports']['ExportsCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['exports']['ExportsCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['exports']['ExportsCollection']['ResetSummary']();
}
