// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['exports']['ExportsCollection']['AccumulateItem'](arg1, arg2);
}

export function ClearApprovalsBucket() {
  return window['go']['exports']['ExportsCollection']['ClearApprovalsBucket']();
}

export function ClearAssetsBucket() {
  return window['go']['exports']['ExportsCollection']['ClearAssetsBucket']();
}

export function ClearBalancesBucket() {
  return window['go']['exports']['ExportsCollection']['ClearBalancesBucket']();
}

export function ClearLogsBucket() {
  return window['go']['exports']['ExportsCollection']['ClearLogsBucket']();
}

export function ClearReceiptsBucket() {
  return window['go']['exports']['ExportsCollection']['ClearReceiptsBucket']();
}

export function ClearStatementsBucket() {
  return window['go']['exports']['ExportsCollection']['ClearStatementsBucket']();
}

export function ClearTracesBucket() {
  return window['go']['exports']['ExportsCollection']['ClearTracesBucket']();
}

export function ClearTransactionsBucket() {
  return window['go']['exports']['ExportsCollection']['ClearTransactionsBucket']();
}

export function ClearTransfersBucket() {
  return window['go']['exports']['ExportsCollection']['ClearTransfersBucket']();
}

export function ClearWithdrawalsBucket() {
  return window['go']['exports']['ExportsCollection']['ClearWithdrawalsBucket']();
}

export function Crud(arg1, arg2, arg3) {
  return window['go']['exports']['ExportsCollection']['Crud'](arg1, arg2, arg3);
}

export function ExportData(arg1) {
  return window['go']['exports']['ExportsCollection']['ExportData'](arg1);
}

export function GetBuckets(arg1) {
  return window['go']['exports']['ExportsCollection']['GetBuckets'](arg1);
}

export function GetConfig() {
  return window['go']['exports']['ExportsCollection']['GetConfig']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['exports']['ExportsCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStoreName(arg1, arg2, arg3) {
  return window['go']['exports']['ExportsCollection']['GetStoreName'](arg1, arg2, arg3);
}

export function GetSummary() {
  return window['go']['exports']['ExportsCollection']['GetSummary']();
}

export function GetSupportedFacets() {
  return window['go']['exports']['ExportsCollection']['GetSupportedFacets']();
}

export function LoadData(arg1) {
  return window['go']['exports']['ExportsCollection']['LoadData'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['exports']['ExportsCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['exports']['ExportsCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['exports']['ExportsCollection']['ResetSummary']();
}
