// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['names']['NamesCollection']['AccumulateItem'](arg1, arg2);
}

export function ChangeVisibility(arg1) {
  return window['go']['names']['NamesCollection']['ChangeVisibility'](arg1);
}

export function Crud(arg1, arg2, arg3) {
  return window['go']['names']['NamesCollection']['Crud'](arg1, arg2, arg3);
}

export function ExportData(arg1) {
  return window['go']['names']['NamesCollection']['ExportData'](arg1);
}

export function FetchByFacet(arg1) {
  return window['go']['names']['NamesCollection']['FetchByFacet'](arg1);
}

export function GetBuckets(arg1) {
  return window['go']['names']['NamesCollection']['GetBuckets'](arg1);
}

export function GetConfig() {
  return window['go']['names']['NamesCollection']['GetConfig']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['names']['NamesCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSummary() {
  return window['go']['names']['NamesCollection']['GetSummary']();
}

export function NeedsUpdate(arg1) {
  return window['go']['names']['NamesCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['names']['NamesCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['names']['NamesCollection']['ResetSummary']();
}
