// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['status']['StatusCollection']['AccumulateItem'](arg1, arg2);
}

export function ExportData(arg1) {
  return window['go']['status']['StatusCollection']['ExportData'](arg1);
}

export function FetchByFacet(arg1) {
  return window['go']['status']['StatusCollection']['FetchByFacet'](arg1);
}

export function GetBuckets(arg1) {
  return window['go']['status']['StatusCollection']['GetBuckets'](arg1);
}

export function GetConfig() {
  return window['go']['status']['StatusCollection']['GetConfig']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['status']['StatusCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSummary() {
  return window['go']['status']['StatusCollection']['GetSummary']();
}

export function NeedsUpdate(arg1) {
  return window['go']['status']['StatusCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['status']['StatusCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['status']['StatusCollection']['ResetSummary']();
}
