// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['contracts']['ContractsCollection']['AccumulateItem'](arg1, arg2);
}

export function ExportData(arg1) {
  return window['go']['contracts']['ContractsCollection']['ExportData'](arg1);
}

export function FetchByFacet(arg1) {
  return window['go']['contracts']['ContractsCollection']['FetchByFacet'](arg1);
}

export function GetBuckets(arg1) {
  return window['go']['contracts']['ContractsCollection']['GetBuckets'](arg1);
}

export function GetConfig() {
  return window['go']['contracts']['ContractsCollection']['GetConfig']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['contracts']['ContractsCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStoreName(arg1, arg2) {
  return window['go']['contracts']['ContractsCollection']['GetStoreName'](arg1, arg2);
}

export function GetSummary() {
  return window['go']['contracts']['ContractsCollection']['GetSummary']();
}

export function GetSupportedFacets() {
  return window['go']['contracts']['ContractsCollection']['GetSupportedFacets']();
}

export function NeedsUpdate(arg1) {
  return window['go']['contracts']['ContractsCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['contracts']['ContractsCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['contracts']['ContractsCollection']['ResetSummary']();
}
