openapi: 3.0.0
info:
  title: TrueBlocks API
  description: An API for accessing cached Ethereum blockchain data and accounts
  contact:
    email: jrush@quickblocks.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.8.04
servers:
- url: https://virtserver.swaggerhub.com/trueblocks/TrueBlocks/0.8.04
  description: SwaggerHub API Auto Mocking
tags:
- name: Scraper
  description: Control the TrueBlocks scraper and build the index
- name: Accounts
  description: List, export, and cache address-based transactional data
- name: Blockchain
  description: Access and cache blockchain-related data
paths:
  /scrape:
    get:
      tags:
      - Scraper
      summary: searches inventory
      description: Allows you to control the index
      operationId: searchInventory
      parameters:
      - name: mode
        in: query
        description: control the block and account scrapers
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - run
          - quit
          - pause
          - restart
      - name: tool
        in: query
        description: process the index, monitors, or both (none means process timestamps
          only)
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - index
          - monitors
          - none
          - both
      - name: pin
        in: query
        description: pin new chunks (and blooms) to IPFS (requires Pinata key)
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - ""
          - "true"
      - name: publish
        in: query
        description: publish the hash of the pin manifest to the UnchainedIndex smart
          contract
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - ""
          - "true"
      - name: sleep
        in: query
        description: the number of seconds to sleep between passes (default 14)
        required: false
        style: form
        explode: true
        schema:
          type: number
      responses:
        "200":
          description: status of the scraper
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/response'
        "400":
          description: bad input parameter
components:
  schemas:
    response:
      required:
      - result
      type: object
      properties:
        data:
          type: object
          example:
          - $ref: '#/components/schemas/scrape_response'
          - $ref: '#/components/schemas/trans_response'
        error:
          type: array
          example:
          - error 1
          - error 2
          items:
            type: string
    scrape_response:
      type: string
      example: Scrape response
    trans_response:
      type: string
      example: Trans response
