// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {sdk} from '../models';

export function AccumulateItem(arg1:any,arg2:types.Summary):Promise<void>;

export function ExportData(arg1:types.Payload):Promise<string>;

export function GetBuckets(arg1:types.Payload):Promise<types.Buckets>;

export function GetConfig():Promise<types.ViewConfig>;

export function GetPage(arg1:types.Payload,arg2:number,arg3:number,arg4:sdk.SortSpec,arg5:string):Promise<types.Page>;

export function GetStoreName(arg1:types.DataFacet,arg2:string,arg3:string):Promise<string>;

export function GetSummary():Promise<types.Summary>;

export function GetSupportedFacets():Promise<Array<types.DataFacet>>;

export function LoadData(arg1:types.DataFacet):Promise<void>;

export function NeedsUpdate(arg1:types.DataFacet):Promise<boolean>;

export function Reset(arg1:types.DataFacet):Promise<void>;

export function ResetSummary():Promise<void>;
