// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['comparitoor']['ComparitoorCollection']['AccumulateItem'](arg1, arg2);
}

export function ExportData(arg1) {
  return window['go']['comparitoor']['ComparitoorCollection']['ExportData'](arg1);
}

export function FetchByFacet(arg1) {
  return window['go']['comparitoor']['ComparitoorCollection']['FetchByFacet'](arg1);
}

export function GetBuckets(arg1) {
  return window['go']['comparitoor']['ComparitoorCollection']['GetBuckets'](arg1);
}

export function GetConfig() {
  return window['go']['comparitoor']['ComparitoorCollection']['GetConfig']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['comparitoor']['ComparitoorCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSummary() {
  return window['go']['comparitoor']['ComparitoorCollection']['GetSummary']();
}

export function NeedsUpdate(arg1) {
  return window['go']['comparitoor']['ComparitoorCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['comparitoor']['ComparitoorCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['comparitoor']['ComparitoorCollection']['ResetSummary']();
}
