export type hash = string;
export type blknum = number;
export type date = string;
export type address = string;
export type timestamp = number;
export type wei = string;
export type int256 = string;
export type uint256 = string;
export type gas = string;
export type uint64 = number;
export type int64 = number;
export type double = number;
export type bytes32 = string;
export type TopicArray = string[];
export * from '@modules/types/Accountname';
export * from '@modules/types/AssetHistory';
export * from '@modules/types/Balance';
export * from '@modules/types/ItemCounter';
export * from '@modules/types/Reconciliation';
export * from '@modules/types/Tag';
