// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['monitors']['MonitorsCollection']['AccumulateItem'](arg1, arg2);
}

export function Clean(arg1, arg2) {
  return window['go']['monitors']['MonitorsCollection']['Clean'](arg1, arg2);
}

export function Crud(arg1, arg2, arg3) {
  return window['go']['monitors']['MonitorsCollection']['Crud'](arg1, arg2, arg3);
}

export function ExportData(arg1) {
  return window['go']['monitors']['MonitorsCollection']['ExportData'](arg1);
}

export function FetchByFacet(arg1) {
  return window['go']['monitors']['MonitorsCollection']['FetchByFacet'](arg1);
}

export function GetBuckets(arg1) {
  return window['go']['monitors']['MonitorsCollection']['GetBuckets'](arg1);
}

export function GetConfig() {
  return window['go']['monitors']['MonitorsCollection']['GetConfig']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['monitors']['MonitorsCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSummary() {
  return window['go']['monitors']['MonitorsCollection']['GetSummary']();
}

export function NeedsUpdate(arg1) {
  return window['go']['monitors']['MonitorsCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['monitors']['MonitorsCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['monitors']['MonitorsCollection']['ResetSummary']();
}
