// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbisCrud(arg1, arg2, arg3) {
  return window['go']['app']['App']['AbisCrud'](arg1, arg2, arg3);
}

export function AddAddressToProject(arg1) {
  return window['go']['app']['App']['AddAddressToProject'](arg1);
}

export function AddAddressesToProject(arg1) {
  return window['go']['app']['App']['AddAddressesToProject'](arg1);
}

export function CancelFetches() {
  return window['go']['app']['App']['CancelFetches']();
}

export function ChangeImageStorageLocation(arg1) {
  return window['go']['app']['App']['ChangeImageStorageLocation'](arg1);
}

export function ChangeVisibility(arg1) {
  return window['go']['app']['App']['ChangeVisibility'](arg1);
}

export function ClearActiveProject() {
  return window['go']['app']['App']['ClearActiveProject']();
}

export function ClearFilterState(arg1) {
  return window['go']['app']['App']['ClearFilterState'](arg1);
}

export function CloseActiveProject() {
  return window['go']['app']['App']['CloseActiveProject']();
}

export function CloseProject(arg1) {
  return window['go']['app']['App']['CloseProject'](arg1);
}

export function ConfigOk() {
  return window['go']['app']['App']['ConfigOk']();
}

export function ConvertToAddress(arg1) {
  return window['go']['app']['App']['ConvertToAddress'](arg1);
}

export function DeleteCustomSkin(arg1) {
  return window['go']['app']['App']['DeleteCustomSkin'](arg1);
}

export function DressesCrud(arg1, arg2, arg3) {
  return window['go']['app']['App']['DressesCrud'](arg1, arg2, arg3);
}

export function Encode(arg1, arg2) {
  return window['go']['app']['App']['Encode'](arg1, arg2);
}

export function ExecuteRowAction(arg1) {
  return window['go']['app']['App']['ExecuteRowAction'](arg1);
}

export function ExportData(arg1) {
  return window['go']['app']['App']['ExportData'](arg1);
}

export function ExportSkin(arg1) {
  return window['go']['app']['App']['ExportSkin'](arg1);
}

export function FileNew(arg1) {
  return window['go']['app']['App']['FileNew'](arg1);
}

export function FileOpen(arg1) {
  return window['go']['app']['App']['FileOpen'](arg1);
}

export function FileQuit(arg1) {
  return window['go']['app']['App']['FileQuit'](arg1);
}

export function FileSave(arg1) {
  return window['go']['app']['App']['FileSave'](arg1);
}

export function FileSaveAs(arg1) {
  return window['go']['app']['App']['FileSaveAs'](arg1);
}

export function FromTemplate(arg1, arg2) {
  return window['go']['app']['App']['FromTemplate'](arg1, arg2);
}

export function GetAbisBuckets(arg1) {
  return window['go']['app']['App']['GetAbisBuckets'](arg1);
}

export function GetAbisConfig(arg1) {
  return window['go']['app']['App']['GetAbisConfig'](arg1);
}

export function GetAbisPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetAbisPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAbisSummary(arg1) {
  return window['go']['app']['App']['GetAbisSummary'](arg1);
}

export function GetActiveProject() {
  return window['go']['app']['App']['GetActiveProject']();
}

export function GetActiveProjectData() {
  return window['go']['app']['App']['GetActiveProjectData']();
}

export function GetActiveProjectPath() {
  return window['go']['app']['App']['GetActiveProjectPath']();
}

export function GetAllSkins() {
  return window['go']['app']['App']['GetAllSkins']();
}

export function GetAppId() {
  return window['go']['app']['App']['GetAppId']();
}

export function GetAppPreferences() {
  return window['go']['app']['App']['GetAppPreferences']();
}

export function GetAvailableSkins() {
  return window['go']['app']['App']['GetAvailableSkins']();
}

export function GetChainList() {
  return window['go']['app']['App']['GetChainList']();
}

export function GetChunksBuckets(arg1) {
  return window['go']['app']['App']['GetChunksBuckets'](arg1);
}

export function GetChunksConfig(arg1) {
  return window['go']['app']['App']['GetChunksConfig'](arg1);
}

export function GetChunksMetric(arg1) {
  return window['go']['app']['App']['GetChunksMetric'](arg1);
}

export function GetChunksPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetChunksPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetChunksSummary(arg1) {
  return window['go']['app']['App']['GetChunksSummary'](arg1);
}

export function GetComparitoorBuckets(arg1) {
  return window['go']['app']['App']['GetComparitoorBuckets'](arg1);
}

export function GetComparitoorConfig(arg1) {
  return window['go']['app']['App']['GetComparitoorConfig'](arg1);
}

export function GetComparitoorPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetComparitoorPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetComparitoorSummary(arg1) {
  return window['go']['app']['App']['GetComparitoorSummary'](arg1);
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetContractsBuckets(arg1) {
  return window['go']['app']['App']['GetContractsBuckets'](arg1);
}

export function GetContractsConfig(arg1) {
  return window['go']['app']['App']['GetContractsConfig'](arg1);
}

export function GetContractsPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetContractsPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetContractsSummary(arg1) {
  return window['go']['app']['App']['GetContractsSummary'](arg1);
}

export function GetDalleAudioURL(arg1, arg2) {
  return window['go']['app']['App']['GetDalleAudioURL'](arg1, arg2);
}

export function GetDebugCollapsed() {
  return window['go']['app']['App']['GetDebugCollapsed']();
}

export function GetDefaultAppPreferences() {
  return window['go']['app']['App']['GetDefaultAppPreferences']();
}

export function GetDressesBuckets(arg1) {
  return window['go']['app']['App']['GetDressesBuckets'](arg1);
}

export function GetDressesConfig(arg1) {
  return window['go']['app']['App']['GetDressesConfig'](arg1);
}

export function GetDressesPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetDressesPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetDressesSummary(arg1) {
  return window['go']['app']['App']['GetDressesSummary'](arg1);
}

export function GetExportsBuckets(arg1) {
  return window['go']['app']['App']['GetExportsBuckets'](arg1);
}

export function GetExportsConfig(arg1) {
  return window['go']['app']['App']['GetExportsConfig'](arg1);
}

export function GetExportsMetric(arg1) {
  return window['go']['app']['App']['GetExportsMetric'](arg1);
}

export function GetExportsPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetExportsPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetExportsSummary(arg1) {
  return window['go']['app']['App']['GetExportsSummary'](arg1);
}

export function GetFilename() {
  return window['go']['app']['App']['GetFilename']();
}

export function GetFilterState(arg1) {
  return window['go']['app']['App']['GetFilterState'](arg1);
}

export function GetFormat() {
  return window['go']['app']['App']['GetFormat']();
}

export function GetImageURL(arg1) {
  return window['go']['app']['App']['GetImageURL'](arg1);
}

export function GetKhedraControlURL() {
  return window['go']['app']['App']['GetKhedraControlURL']();
}

export function GetLanguage() {
  return window['go']['app']['App']['GetLanguage']();
}

export function GetLastFacet(arg1) {
  return window['go']['app']['App']['GetLastFacet'](arg1);
}

export function GetLastView() {
  return window['go']['app']['App']['GetLastView']();
}

export function GetMarkdown(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetMarkdown'](arg1, arg2, arg3);
}

export function GetMonitorsBuckets(arg1) {
  return window['go']['app']['App']['GetMonitorsBuckets'](arg1);
}

export function GetMonitorsConfig(arg1) {
  return window['go']['app']['App']['GetMonitorsConfig'](arg1);
}

export function GetMonitorsPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetMonitorsPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetMonitorsSummary(arg1) {
  return window['go']['app']['App']['GetMonitorsSummary'](arg1);
}

export function GetNamesBuckets(arg1) {
  return window['go']['app']['App']['GetNamesBuckets'](arg1);
}

export function GetNamesConfig(arg1) {
  return window['go']['app']['App']['GetNamesConfig'](arg1);
}

export function GetNamesPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetNamesPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetNamesSummary(arg1) {
  return window['go']['app']['App']['GetNamesSummary'](arg1);
}

export function GetNodeStatus(arg1) {
  return window['go']['app']['App']['GetNodeStatus'](arg1);
}

export function GetOpenProjects() {
  return window['go']['app']['App']['GetOpenProjects']();
}

export function GetOrgPreferences() {
  return window['go']['app']['App']['GetOrgPreferences']();
}

export function GetProjectAddress() {
  return window['go']['app']['App']['GetProjectAddress']();
}

export function GetProjectViewState(arg1) {
  return window['go']['app']['App']['GetProjectViewState'](arg1);
}

export function GetProjectsBuckets(arg1) {
  return window['go']['app']['App']['GetProjectsBuckets'](arg1);
}

export function GetProjectsConfig(arg1) {
  return window['go']['app']['App']['GetProjectsConfig'](arg1);
}

export function GetProjectsPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetProjectsPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetProjectsSummary(arg1) {
  return window['go']['app']['App']['GetProjectsSummary'](arg1);
}

export function GetRegisteredViews() {
  return window['go']['app']['App']['GetRegisteredViews']();
}

export function GetSkin() {
  return window['go']['app']['App']['GetSkin']();
}

export function GetSkinByName(arg1) {
  return window['go']['app']['App']['GetSkinByName'](arg1);
}

export function GetStatusBuckets(arg1) {
  return window['go']['app']['App']['GetStatusBuckets'](arg1);
}

export function GetStatusConfig(arg1) {
  return window['go']['app']['App']['GetStatusConfig'](arg1);
}

export function GetStatusPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetStatusPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStatusSummary(arg1) {
  return window['go']['app']['App']['GetStatusSummary'](arg1);
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function GetUserInfoStatus() {
  return window['go']['app']['App']['GetUserInfoStatus']();
}

export function GetUserPreferences() {
  return window['go']['app']['App']['GetUserPreferences']();
}

export function GetWizardReturn() {
  return window['go']['app']['App']['GetWizardReturn']();
}

export function HandleProjectsRowAction(arg1) {
  return window['go']['app']['App']['HandleProjectsRowAction'](arg1);
}

export function HasActiveProject() {
  return window['go']['app']['App']['HasActiveProject']();
}

export function ImportSkin(arg1) {
  return window['go']['app']['App']['ImportSkin'](arg1);
}

export function IsDialogSilenced(arg1) {
  return window['go']['app']['App']['IsDialogSilenced'](arg1);
}

export function IsDisabled(arg1) {
  return window['go']['app']['App']['IsDisabled'](arg1);
}

export function IsInitialized() {
  return window['go']['app']['App']['IsInitialized']();
}

export function IsReady() {
  return window['go']['app']['App']['IsReady']();
}

export function LogFrontend(arg1) {
  return window['go']['app']['App']['LogFrontend'](arg1);
}

export function MonitorsClean(arg1, arg2) {
  return window['go']['app']['App']['MonitorsClean'](arg1, arg2);
}

export function MonitorsCrud(arg1, arg2, arg3) {
  return window['go']['app']['App']['MonitorsCrud'](arg1, arg2, arg3);
}

export function NameFromAddress(arg1) {
  return window['go']['app']['App']['NameFromAddress'](arg1);
}

export function NamesCrud(arg1, arg2, arg3) {
  return window['go']['app']['App']['NamesCrud'](arg1, arg2, arg3);
}

export function NewProject(arg1, arg2) {
  return window['go']['app']['App']['NewProject'](arg1, arg2);
}

export function OpenProjectFile(arg1) {
  return window['go']['app']['App']['OpenProjectFile'](arg1);
}

export function ReadToMe(arg1, arg2) {
  return window['go']['app']['App']['ReadToMe'](arg1, arg2);
}

export function RegisterCollection(arg1) {
  return window['go']['app']['App']['RegisterCollection'](arg1);
}

export function Reload(arg1) {
  return window['go']['app']['App']['Reload'](arg1);
}

export function ReloadAbis(arg1) {
  return window['go']['app']['App']['ReloadAbis'](arg1);
}

export function ReloadChunks(arg1) {
  return window['go']['app']['App']['ReloadChunks'](arg1);
}

export function ReloadComparitoor(arg1) {
  return window['go']['app']['App']['ReloadComparitoor'](arg1);
}

export function ReloadContracts(arg1) {
  return window['go']['app']['App']['ReloadContracts'](arg1);
}

export function ReloadDresses(arg1) {
  return window['go']['app']['App']['ReloadDresses'](arg1);
}

export function ReloadExports(arg1) {
  return window['go']['app']['App']['ReloadExports'](arg1);
}

export function ReloadMonitors(arg1) {
  return window['go']['app']['App']['ReloadMonitors'](arg1);
}

export function ReloadNames(arg1) {
  return window['go']['app']['App']['ReloadNames'](arg1);
}

export function ReloadProjects(arg1) {
  return window['go']['app']['App']['ReloadProjects'](arg1);
}

export function ReloadSkins() {
  return window['go']['app']['App']['ReloadSkins']();
}

export function ReloadStatus(arg1) {
  return window['go']['app']['App']['ReloadStatus'](arg1);
}

export function RemoveAddressFromProject(arg1) {
  return window['go']['app']['App']['RemoveAddressFromProject'](arg1);
}

export function RestoreProjectContext(arg1) {
  return window['go']['app']['App']['RestoreProjectContext'](arg1);
}

export function SaveBounds(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveBounds'](arg1, arg2, arg3, arg4);
}

export function SaveProject() {
  return window['go']['app']['App']['SaveProject']();
}

export function SetActiveAddress(arg1) {
  return window['go']['app']['App']['SetActiveAddress'](arg1);
}

export function SetActiveChain(arg1) {
  return window['go']['app']['App']['SetActiveChain'](arg1);
}

export function SetActiveContract(arg1) {
  return window['go']['app']['App']['SetActiveContract'](arg1);
}

export function SetActivePeriod(arg1) {
  return window['go']['app']['App']['SetActivePeriod'](arg1);
}

export function SetActiveProjectPath(arg1) {
  return window['go']['app']['App']['SetActiveProjectPath'](arg1);
}

export function SetAppPreferences(arg1) {
  return window['go']['app']['App']['SetAppPreferences'](arg1);
}

export function SetChain(arg1) {
  return window['go']['app']['App']['SetChain'](arg1);
}

export function SetChromeCollapsed(arg1) {
  return window['go']['app']['App']['SetChromeCollapsed'](arg1);
}

export function SetChunksMetric(arg1, arg2) {
  return window['go']['app']['App']['SetChunksMetric'](arg1, arg2);
}

export function SetDebugCollapsed(arg1) {
  return window['go']['app']['App']['SetDebugCollapsed'](arg1);
}

export function SetExportsMetric(arg1, arg2) {
  return window['go']['app']['App']['SetExportsMetric'](arg1, arg2);
}

export function SetFilterState(arg1, arg2) {
  return window['go']['app']['App']['SetFilterState'](arg1, arg2);
}

export function SetFormat(arg1) {
  return window['go']['app']['App']['SetFormat'](arg1);
}

export function SetHelpCollapsed(arg1) {
  return window['go']['app']['App']['SetHelpCollapsed'](arg1);
}

export function SetInitialized(arg1) {
  return window['go']['app']['App']['SetInitialized'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetLastFacet(arg1, arg2) {
  return window['go']['app']['App']['SetLastFacet'](arg1, arg2);
}

export function SetLastView(arg1) {
  return window['go']['app']['App']['SetLastView'](arg1);
}

export function SetMenuCollapsed(arg1) {
  return window['go']['app']['App']['SetMenuCollapsed'](arg1);
}

export function SetOrgPreferences(arg1) {
  return window['go']['app']['App']['SetOrgPreferences'](arg1);
}

export function SetProjectAddress(arg1) {
  return window['go']['app']['App']['SetProjectAddress'](arg1);
}

export function SetProjectViewState(arg1, arg2) {
  return window['go']['app']['App']['SetProjectViewState'](arg1, arg2);
}

export function SetSkin(arg1) {
  return window['go']['app']['App']['SetSkin'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['app']['App']['SetTheme'](arg1);
}

export function SetUserInfo(arg1, arg2) {
  return window['go']['app']['App']['SetUserInfo'](arg1, arg2);
}

export function SetUserPreferences(arg1) {
  return window['go']['app']['App']['SetUserPreferences'](arg1);
}

export function SetViewAndFacet(arg1, arg2) {
  return window['go']['app']['App']['SetViewAndFacet'](arg1, arg2);
}

export function SilenceDialog(arg1) {
  return window['go']['app']['App']['SilenceDialog'](arg1);
}

export function Speak(arg1, arg2) {
  return window['go']['app']['App']['Speak'](arg1, arg2);
}

export function SwitchToProject(arg1) {
  return window['go']['app']['App']['SwitchToProject'](arg1);
}

export function ValidateActiveProject() {
  return window['go']['app']['App']['ValidateActiveProject']();
}
