// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['projects']['ProjectsCollection']['AccumulateItem'](arg1, arg2);
}

export function ChangeVisibility(arg1) {
  return window['go']['projects']['ProjectsCollection']['ChangeVisibility'](arg1);
}

export function ExportData(arg1) {
  return window['go']['projects']['ProjectsCollection']['ExportData'](arg1);
}

export function FetchByFacet(arg1) {
  return window['go']['projects']['ProjectsCollection']['FetchByFacet'](arg1);
}

export function GetBuckets(arg1) {
  return window['go']['projects']['ProjectsCollection']['GetBuckets'](arg1);
}

export function GetConfig() {
  return window['go']['projects']['ProjectsCollection']['GetConfig']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['projects']['ProjectsCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSummary(arg1) {
  return window['go']['projects']['ProjectsCollection']['GetSummary'](arg1);
}

export function HandleRowAction(arg1) {
  return window['go']['projects']['ProjectsCollection']['HandleRowAction'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['projects']['ProjectsCollection']['NeedsUpdate'](arg1);
}

export function OnProjectClosed(arg1) {
  return window['go']['projects']['ProjectsCollection']['OnProjectClosed'](arg1);
}

export function Reset(arg1) {
  return window['go']['projects']['ProjectsCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['projects']['ProjectsCollection']['ResetSummary']();
}
