// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['dresses']['DressesCollection']['AccumulateItem'](arg1, arg2);
}

export function Crud(arg1, arg2, arg3) {
  return window['go']['dresses']['DressesCollection']['Crud'](arg1, arg2, arg3);
}

export function ExportData(arg1) {
  return window['go']['dresses']['DressesCollection']['ExportData'](arg1);
}

export function FetchByFacet(arg1) {
  return window['go']['dresses']['DressesCollection']['FetchByFacet'](arg1);
}

export function GetBuckets(arg1) {
  return window['go']['dresses']['DressesCollection']['GetBuckets'](arg1);
}

export function GetConfig() {
  return window['go']['dresses']['DressesCollection']['GetConfig']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['dresses']['DressesCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStoreName(arg1, arg2) {
  return window['go']['dresses']['DressesCollection']['GetStoreName'](arg1, arg2);
}

export function GetSummary() {
  return window['go']['dresses']['DressesCollection']['GetSummary']();
}

export function GetSupportedFacets() {
  return window['go']['dresses']['DressesCollection']['GetSupportedFacets']();
}

export function NeedsUpdate(arg1) {
  return window['go']['dresses']['DressesCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['dresses']['DressesCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['dresses']['DressesCollection']['ResetSummary']();
}
