// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['chunks']['ChunksCollection']['AccumulateItem'](arg1, arg2);
}

export function Crud(arg1, arg2, arg3) {
  return window['go']['chunks']['ChunksCollection']['Crud'](arg1, arg2, arg3);
}

export function ExportData(arg1) {
  return window['go']['chunks']['ChunksCollection']['ExportData'](arg1);
}

export function GetBuckets(arg1) {
  return window['go']['chunks']['ChunksCollection']['GetBuckets'](arg1);
}

export function GetConfig() {
  return window['go']['chunks']['ChunksCollection']['GetConfig']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['chunks']['ChunksCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStoreName(arg1, arg2, arg3) {
  return window['go']['chunks']['ChunksCollection']['GetStoreName'](arg1, arg2, arg3);
}

export function GetSummary() {
  return window['go']['chunks']['ChunksCollection']['GetSummary']();
}

export function GetSupportedFacets() {
  return window['go']['chunks']['ChunksCollection']['GetSupportedFacets']();
}

export function LoadData(arg1) {
  return window['go']['chunks']['ChunksCollection']['LoadData'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['chunks']['ChunksCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['chunks']['ChunksCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['chunks']['ChunksCollection']['ResetSummary']();
}
