// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {base} from '../models';
import {project} from '../models';
import {types} from '../models';

export function AddAddress(arg1:base.Address):Promise<void>;

export function AddContract(arg1:string):Promise<void>;

export function ClearAllFilterStates():Promise<void>;

export function ClearFilterState(arg1:project.ViewStateKey):Promise<void>;

export function GetActiveAddress():Promise<base.Address>;

export function GetActiveChain():Promise<string>;

export function GetActiveContract():Promise<string>;

export function GetActivePeriod():Promise<types.Period>;

export function GetAddresses():Promise<Array<base.Address>>;

export function GetChains():Promise<Array<string>>;

export function GetContracts():Promise<Array<string>>;

export function GetFilterState(arg1:project.ViewStateKey):Promise<project.FilterState|boolean>;

export function GetLastFacet(arg1:string):Promise<string>;

export function GetLastView():Promise<string>;

export function GetName():Promise<string>;

export function GetPath():Promise<string>;

export function GetViewStates(arg1:string):Promise<Record<string, project.FilterState>>;

export function RemoveAddress(arg1:base.Address):Promise<void>;

export function RemoveContract(arg1:string):Promise<void>;

export function Save():Promise<void>;

export function SaveAs(arg1:string):Promise<void>;

export function SetActiveAddress(arg1:base.Address):Promise<void>;

export function SetActiveChain(arg1:string):Promise<void>;

export function SetActiveContract(arg1:string):Promise<void>;

export function SetActivePeriod(arg1:types.Period):Promise<void>;

export function SetFilterState(arg1:project.ViewStateKey,arg2:project.FilterState):Promise<void>;

export function SetLastFacet(arg1:string,arg2:string):Promise<void>;

export function SetLastView(arg1:string):Promise<void>;

export function SetName(arg1:string):Promise<void>;

export function SetViewAndFacet(arg1:string,arg2:string):Promise<void>;

export function SetViewStates(arg1:string,arg2:Record<string, project.FilterState>):Promise<void>;
