// Period enum is now auto-generated by Wails from Go backend
import { types } from '@models';

// Re-export the Wails-generated Period enum for convenience
export const Period = types.Period;
export type PeriodType = types.Period;

// Human-readable labels for the UI
export const PeriodLabels = {
  [Period.BLOCKLY]: 'Raw Data',
  [Period.HOURLY]: 'Hourly',
  [Period.DAILY]: 'Daily',
  [Period.WEEKLY]: 'Weekly',
  [Period.MONTHLY]: 'Monthly',
  [Period.QUARTERLY]: 'Quarterly',
  [Period.ANNUAL]: 'Annual',
} as const;

// Options for Select components
export const PeriodOptions = Object.entries(PeriodLabels).map(
  ([value, label]) => ({
    value,
    label,
  }),
);
