name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # GoLang version
          go-version: '1.23.8'
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev
      - name: Verify pkg-config installation
        run: |
          pkg-config --version
      - name: Set Go environment variables
        run: |
          echo "GOMODCACHE=$HOME/go/pkg/mod" >> $GITHUB_ENV
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
      - name: Install Wails CLI
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install
      - name: Run React Lint (ESLint)
        run: |
          cd frontend
          yarn eslint .
      - name: Build Frontend
        run: |
          cd frontend
          yarn build
      - name: Remove replace directive from go.mod
        run: |
          sed -i '/^replace/d' go.mod
      - name: Show modified go.mod
        run: |
          cat go.mod
      - name: Download go requirements
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u ./...
      - name: Run Go Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Build Wails Application
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go mod tidy
          wails build -tags webkit2_41
