name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
env:
  # GoLang version
  GO_VERSION: "1.23.8"
  NODE_VERSION: "20"
jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate Changelog
        id: changelog
        run: |
          echo "changes=$(git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:'- %s')" >> $GITHUB_OUTPUT
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "trueblocks-explorer ${{ github.ref_name }}"
          body: |
            # Changelog

            ${{ steps.changelog.outputs.changes }}
          draft: true
          prerelease: false
  build_macos:
    runs-on: macos-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Build Frontend
        run: |
          cd frontend
          yarn build
      - name: Build macOS binary
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          wails build -platform darwin/universal
      - name: Upload macOS dmg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/bin/trueblocks-explorer.dmg
          asset_name: trueblocks-explorer-${{ github.ref_name }}-macos.dmg
          asset_content_type: application/octet-stream
  build_linux:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Build Frontend
        run: |
          cd frontend
          yarn build
      - name: Build Linux binary
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          wails build -platform linux/amd64
      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/bin/trueblocks-explorer
          asset_name: trueblocks-explorer-${{ github.ref_name }}-linux
          asset_content_type: application/octet-streams
